title: Hocus Pocus
subtitle: A little bit of this. A little bit of that.
description: Ramblings of a failed engineer.
keywords: >-
  rant, politics, digital india, technology, phones, windows, world, bollywood,
  hollywood, movies, reviews
author: Navjot Singh
language: en
timezone: Asia/Kolkata
url: 'https://diary.nspeaks.com'
root: /
permalink: ':year/:month/:day/:title/'
permalink_defaults: null
pretty_urls:
  trailing_index: true
  trailing_html: true
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
marked:
  prependRoot: true
  postAsset: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''
index_generator:
  path: ''
  per_page: 10
  order_by: '-date'
default_category: rants
category_map: null
tag_map: null
meta_generator: true
date_format: DD-MM-YYYY
time_format: 'HH:mm:ss'
updated_option: mtime
per_page: 10
pagination_dir: page
include: null
exclude: null
ignore: null
theme: icarus
deploy:
  type: ''
alias:
  lets-hate-45381e46198a/index.html: 'https://diary.nspeaks.com/2019/02/16/Let%E2%80%99s-hate/'
  digital-india-is-a-myth-74f3e3c74ec0/index.html: 'https://diary.nspeaks.com/2015/09/28/Digital-India-is-a-myth/'
feed:
    enable: true
    type: atom
    path: atom.xml
    limit: 20
    content: true
