#title in header
title: "Hocus Pocus"

#main info
#owner
owner: "I am Navjot Singh (He/him)"
email: diary@nspeaks.com
info: "A freelance technical writer and web developer from India."
#description
desc: "This is my personal diary where I put out random stuff and sometimes talk about the movies and shows I love."

#menu
menu:
  NSpeaks: https://nspeaks.com

#index/main page max show posts (in number)
max_post: 4

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: 

# social profile at the footer/bottom
footer: true
placename: 
placelink: 
github: https://github.com/navjotjsingh
linkedin: 
twitter: https://twitter.com/nspeaks
instagram: 

# Misc
nanobar: /js/nanobar.min.js
switch_light: ☀️
switch_dark: 🌑

# favicon
favicon: /images/favicon.ico
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
disqus_shortname: https-adisaktijrs-github-io
